//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASSCOMPORT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class tr_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal tr_local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BASSCOMPORT.tr_local", typeof(tr_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen ürün etiketi üzerinde bulunan ölçeklendirme aralığını kontrol ediniz. Ardından minimum ve maksimum değerleri belirtilen kutucuklara giriniz ve AYARLA butonuna tıklayınız. Bu şekilde cihaza referans ölçeklendirme aralığı vermiş oluyoruz. .
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Hakkında.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlanacak maxScale.
        /// </summary>
        internal static string Ayarlanacak_maxScale {
            get {
                return ResourceManager.GetString("Ayarlanacak maxScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlanacak minScale.
        /// </summary>
        internal static string Ayarlanacak_minScale {
            get {
                return ResourceManager.GetString("Ayarlanacak minScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonra ölçeklendirmek istediğiniz minimum ve maksimum değerleri giriniz ve DEĞİŞTİR butonuna tıklayınız. Lütfen &apos;OK&apos; işaretini görene kadar bekleyiniz..
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAUD HIZI.
        /// </summary>
        internal static string BAUD_RATE {
            get {
                return ResourceManager.GetString("BAUD RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖLÇEKLENDİR.
        /// </summary>
        internal static string CHANGE {
            get {
                return ResourceManager.GetString("CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYARLA.
        /// </summary>
        internal static string CHANGE2 {
            get {
                return ResourceManager.GetString("CHANGE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAPAT.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri Topla.
        /// </summary>
        internal static string Collect_Data {
            get {
                return ResourceManager.GetString("Collect Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM PORT AYARLARI.
        /// </summary>
        internal static string COM_PORT_SETTINGS {
            get {
                return ResourceManager.GetString("COM PORT SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri ve Excel(3).
        /// </summary>
        internal static string Data_and_Excel_3_ {
            get {
                return ResourceManager.GetString("Data and Excel(3)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERİ BİTİ.
        /// </summary>
        internal static string DATA_BITS {
            get {
                return ResourceManager.GetString("DATA BITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     İzleme.
        /// </summary>
        internal static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehber.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncel maxScale.
        /// </summary>
        internal static string Güncel_maxScale {
            get {
                return ResourceManager.GetString("Güncel maxScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncel minScale.
        /// </summary>
        internal static string Güncel_minScale {
            get {
                return ResourceManager.GetString("Güncel minScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösterge.
        /// </summary>
        internal static string Indıcator {
            get {
                return ResourceManager.GetString("Indıcator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzleme Aralığı(2).
        /// </summary>
        internal static string İnterval_2_ {
            get {
                return ResourceManager.GetString("İnterval(2)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxÖlçek.
        /// </summary>
        internal static string maxScale {
            get {
                return ResourceManager.GetString("maxScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minÖlçek.
        /// </summary>
        internal static string minScale {
            get {
                return ResourceManager.GetString("minScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAĞLAN.
        /// </summary>
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARİTE.
        /// </summary>
        internal static string PARITY {
            get {
                return ResourceManager.GetString("PARITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERCİHLER.
        /// </summary>
        internal static string PREFERENCES {
            get {
                return ResourceManager.GetString("PREFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basınç Birimi.
        /// </summary>
        internal static string Pressure_Unit {
            get {
                return ResourceManager.GetString("Pressure Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Numarası(1).
        /// </summary>
        internal static string Product_Number_1_ {
            get {
                return ResourceManager.GetString("Product Number(1)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veriyi Kaydet(xsl).
        /// </summary>
        internal static string Save_Data_xsl_ {
            get {
                return ResourceManager.GetString("Save Data(xsl)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamanı Kaydet.
        /// </summary>
        internal static string Save_Interval {
            get {
                return ResourceManager.GetString("Save Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Numarasını Kaydet.
        /// </summary>
        internal static string Save_Product_Number {
            get {
                return ResourceManager.GetString("Save Product Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Ölçeklendirme.
        /// </summary>
        internal static string Scaling {
            get {
                return ResourceManager.GetString("Scaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GONDER.
        /// </summary>
        internal static string SEND {
            get {
                return ResourceManager.GetString("SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYARLA.
        /// </summary>
        internal static string SET {
            get {
                return ResourceManager.GetString("SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Ayarlar.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURMA BİTİ.
        /// </summary>
        internal static string STOP_BITS {
            get {
                return ResourceManager.GetString("STOP BITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıcaklık Birimi.
        /// </summary>
        internal static string Temperature_Unit {
            get {
                return ResourceManager.GetString("Temperature Unit", resourceCulture);
            }
        }
    }
}
